# Generated by Django 2.1.7 on 2022-04-19 16:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sql_problems_status',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
