# Generated by Django 2.1.7 on 2022-01-22 23:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(db_index=True, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('description', utils.models.RichTextField()),
                ('test_cases', django.contrib.postgres.fields.jsonb.JSONField()),
                ('total_score', models.IntegerField(default=0)),
                ('template', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(null=True)),
                ('visible', models.BooleanField(default=True)),
                ('source', models.TextField(null=True)),
                ('submission_number', models.BigIntegerField(default=0)),
                ('accepted_number', models.BigIntegerField(default=0)),
                ('statistic_info', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('share_submission', models.BooleanField(default=False)),
                ('problem_data', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sql_problem',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='SqlProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'sql_problem_tag',
            },
        ),
        migrations.AddField(
            model_name='sqlproblem',
            name='tags',
            field=models.ManyToManyField(to='sql.SqlProblemTag'),
        ),
    ]
